/*
 * Copyright (C) 2014 ParanoidAndroid Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative */

#ifndef _Included_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
#define _Included_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
 * Method:    getColors
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative_getColors
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
 * Method:    setScreenSize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative_setScreenSize
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
